# Production Specific Settings
# Use port 5000 for AWS Elastic Beanstalk
server.port=5000

# Enable Actuator for Health Checks
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
